language: python
cache: pip
python:
  - "pypy3"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10-dev"
# command to install dependencies
install: pip install Pygments>=2.5.2
# command to run tests
script: make testone
